# This is used for test_cli.py::test_import_object_from_name
raise RuntimeError("This is a test exception")
